stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - source build_image
  only:
    - main

deploy-job:  
  stage: deploy
  script:
    - docker compose down
    - docker compose up -d
  only:
    - main
  needs:
    - build-job