stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - cd TaskFlow/
    - . build_image

deploy-job:  
  stage: deploy
  script:
    - cd TaskFlow/
    - docker compose down
    - docker compose up -d