"""name to title column in projects model, unique constrait, added project_id to tasks model

Revision ID: 5b954c85e565
Revises: 4a6dae0ad0ea
Create Date: 2026-01-08 01:21:49.226936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b954c85e565'
down_revision: Union[str, Sequence[str], None] = '4a6dae0ad0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint('unique_project_title', 'projects', ['owner_id', 'title'])
    op.drop_column('projects', 'name')
    op.create_unique_constraint('unique_project_task.title', 'tasks', ['project_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_project_task.title', 'tasks', type_='unique')
    op.add_column('projects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_project_title', 'projects', type_='unique')
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
