"""projects column is not nullable now

Revision ID: eca0aa94ff3b
Revises: a4ecb8787537
Create Date: 2026-01-08 20:58:42.133925

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eca0aa94ff3b"
down_revision: Union[str, Sequence[str], None] = "a4ecb8787537"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "project_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "project_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
