"""added Google & GitHub IDs for OAuth 2.0

Revision ID: eb463cdceff0
Revises: 92bd8914086c
Create Date: 2026-01-22 12:50:40.846188

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb463cdceff0"
down_revision: Union[str, Sequence[str], None] = "92bd8914086c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("github_id", sa.String(length=255), nullable=True))
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.create_unique_constraint(None, "users", ["github_id"])
    op.create_unique_constraint(None, "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("users", "github_id")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
